
import React, { useState, useEffect } from 'react';
import { sanitizeHtml } from '@/utils/security';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { 
  Eye, 
  Smartphone, 
  Monitor, 
  Camera, 
  Loader2,
  AlertCircle,
  RefreshCw
} from 'lucide-react';
import { useMetaAdsPreview } from '@/hooks/useMetaAdsPreview';
import { Alert, AlertDescription } from '@/components/ui/alert';

interface AdPreviewWidgetProps {
  adId?: string;
  autoGenerate?: boolean;
  compact?: boolean;
  className?: string;
}

export const AdPreviewWidget: React.FC<AdPreviewWidgetProps> = ({
  adId,
  autoGenerate = false,
  compact = false,
  className = ""
}) => {
  const { 
    previews, 
    isLoading, 
    generatePreview, 
    refreshPreview
  } = useMetaAdsPreview();
  
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

  useEffect(() => {
    if (adId && autoGenerate && !hasAutoGenerated && !isLoading) {
      console.log('🎬 Auto-generating preview for ad:', adId);
      generatePreview(adId, { includeStories: false });
      setHasAutoGenerated(true);
    }
  }, [adId, autoGenerate, hasAutoGenerated, isLoading, generatePreview]);

  const getFormatIcon = (format: string) => {
    switch (format) {
      case 'DESKTOP_FEED_STANDARD':
        return <Monitor className="w-3 h-3" />;
      case 'MOBILE_FEED_STANDARD':
        return <Smartphone className="w-3 h-3" />;
      case 'INSTAGRAM_STANDARD':
        return <Camera className="w-3 h-3" />;
      default:
        return <Monitor className="w-3 h-3" />;
    }
  };

  const getFormatLabel = (preview: any) => {
    const shortNames: Record<string, string> = {
      'DESKTOP_FEED_STANDARD': 'Desktop',
      'MOBILE_FEED_STANDARD': 'Mobile',
      'INSTAGRAM_STANDARD': 'Instagram'
    };
    return shortNames[preview.format] || preview.formatName || preview.format;
  };

  if (!adId) {
    return (
      <Card className={className}>
        <CardHeader className="pb-3">
          <CardTitle className="text-sm flex items-center">
            <Eye className="w-4 h-4 mr-2" />
            Preview do Anúncio
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="text-center py-6 text-gray-500">
            <AlertCircle className="w-8 h-8 mx-auto mb-2 text-gray-400" />
            <p className="text-sm">Anúncio ainda não criado</p>
          </div>
        </CardContent>
      </Card>
    );
  }

  if (compact && previews.length === 0 && !isLoading) {
    return (
      <Card className={className}>
        <CardContent className="pt-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-2">
              <Eye className="w-4 h-4 text-gray-400" />
              <span className="text-sm text-gray-600">Preview</span>
            </div>
            <Button
              onClick={() => generatePreview(adId)}
              disabled={isLoading}
              variant="outline"
              size="sm"
            >
              {isLoading ? (
                <Loader2 className="w-3 h-3 animate-spin" />
              ) : (
                <Eye className="w-3 h-3" />
              )}
            </Button>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className={className}>
      <CardHeader className="pb-3">
        <div className="flex items-center justify-between">
          <div>
            <CardTitle className="text-sm flex items-center">
              <Eye className="w-4 h-4 mr-2" />
              Preview do Anúncio
            </CardTitle>
            {previews.length > 0 && (
              <CardDescription className="text-xs">
                {previews.length} formato(s) disponível(is)
              </CardDescription>
            )}
          </div>
          
          {previews.length > 0 && (
            <Button
              onClick={refreshPreview}
              disabled={isLoading}
              variant="outline"
              size="sm"
            >
              {isLoading ? (
                <Loader2 className="w-3 h-3 animate-spin" />
              ) : (
                <RefreshCw className="w-3 h-3" />
              )}
            </Button>
          )}
        </div>
      </CardHeader>
      
      <CardContent>
        {isLoading ? (
          <div className="text-center py-6">
            <Loader2 className="w-6 h-6 mx-auto mb-2 animate-spin text-blue-600" />
            <p className="text-sm text-gray-600">Gerando preview...</p>
          </div>
        ) : previews.length === 0 ? (
          <div className="text-center py-6 space-y-3">
            <AlertCircle className="w-8 h-8 mx-auto text-gray-400" />
            <div>
              <p className="text-sm font-medium text-gray-900">Preview indisponível</p>
              <p className="text-xs text-gray-500">O anúncio pode não estar pronto ainda</p>
            </div>
            <Button
              onClick={() => generatePreview(adId)}
              disabled={isLoading}
              variant="outline"
              size="sm"
            >
              <Eye className="w-3 h-3 mr-1" />
              Gerar Preview
            </Button>
          </div>
        ) : (
          <Tabs defaultValue={previews[0]?.format || 'DESKTOP_FEED_STANDARD'}>
            <TabsList className="grid w-full grid-cols-3 h-8">
              {previews.slice(0, 3).map((preview) => (
                <TabsTrigger 
                  key={preview.format} 
                  value={preview.format}
                  className="text-xs p-1"
                >
                  <div className="flex items-center space-x-1">
                    {getFormatIcon(preview.format)}
                    <span className="hidden sm:inline">
                      {getFormatLabel(preview)}
                    </span>
                  </div>
                </TabsTrigger>
              ))}
            </TabsList>

            {previews.map((preview) => (
              <TabsContent key={preview.format} value={preview.format} className="mt-3">
                <div className="space-y-2">
                  <Badge variant="outline" className="text-xs">
                    {getFormatLabel(preview)}
                  </Badge>
                  
                  <div className="border rounded-md overflow-hidden bg-white">
                    {preview.body ? (
                       <div 
                         className="preview-container text-xs max-h-48 overflow-auto p-2"
                         dangerouslySetInnerHTML={{ __html: sanitizeHtml(preview.body) }}
                         style={{ fontSize: '10px' }}
                       />
                    ) : (
                      <div className="text-center py-4 text-gray-500">
                        <p className="text-xs">Preview não disponível</p>
                      </div>
                    )}
                  </div>
                </div>
              </TabsContent>
            ))}
          </Tabs>
        )}
      </CardContent>
    </Card>
  );
};
